### ISSUE TITLE
Build our own otel collector distribution

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#339]
In https://github.com/sillsdev/languageforge-lexbox/pull/338 we started using the contrib otel collector distribution, which is about twice as big as the non-contrib distribution:
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/128df739-3dd3-4f59-9c2d-94927911fac2)

Because the contrib distribution contains **everything** it's [recommended/encouraged](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/README.md) to build your own collector image/distribution with just the components you need.

Maybe we don't care about the extra 120 MB... 🤷 

To build our own distribution, we:
1) [Download](https://github.com/open-telemetry/opentelemetry-collector/releases?q=builder&expanded=true) the latest otel-collector-builder (ocb) release
2) Run it with a config of the components we want (see [otelcol-contrib/manifest.yaml](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol-contrib/manifest.yaml) to see how the contrib distribution is configured). I think this is what we're currently using:
```
dist:
  name: lexbox-otelcol-contrib
  description: OpenTelemetry Collector Contrib
  version: 1.0.0
  output_path: ./lexbox-otel-collector-build
  otelcol_version: 0.87.0

extensions:
  - gomod: go.opentelemetry.io/collector/extension/ballastextension v0.87.0 # we're not using this yet, but it's recommended: https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/memorylimiterprocessor/README.md
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.87.0 # we're not using this either, but we might want to

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.87.0
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.87.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.87.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.87.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.87.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.87.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/redactionprocessor v0.87.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.87.0
```
3) Somehow turn the built collector executable into an image and publish it
