### ISSUE TITLE
Restrict hg service to only lexbox container 

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#599]
Currently any service on the cluster can access the hg service directly, but there's no authentication on it. Only lexbox should have access to that service.

**Comment by rmunn** [comment]
The k8s solution is to use NetworkPolicy to restrict access to a service: you can set it up so that only pods matching a certain selector (e.g., name=lexbox and app=lexbox, or label: "hg-access=true") are allowed to connect to the service. This does not protect against a scenario where a bad actor has managed to upload pods to your k8s cluster, but if that has happened you're probably screwed anyway. It does protect against someone managing to hack an unrelated pod in your cluster; that pod would be denied access to the protected service.

A NetworkPolicy example from https://stackoverflow.com/a/68634130 that allows access to the message-broker service only from pods with the label "broker-access: true" (and then only on port 6379, any connection attempts on other ports would be denied):

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: broker-policy
  namespace: default  
spec:
  podSelector:
    matchLabels:
      role: message-broker
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          broker-access: true
    ports:
    - protocol: TCP
      port: 6379
```
