### ISSUE TITLE
support mac os

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#907]
FW lite will require an icu binary to run, we already have those for windows and linux thanks to this [package](https://www.nuget.org/packages/Microsoft.ICU.ICU4C.Runtime). 

To get the binary we can copy what paranext did here:
https://github.com/paranext/paranext-core/pull/942

During build the install ICU via MacPorts
```yaml
      - name: Install MacPorts
        if: ${{ matrix.os == 'macos-latest' }}
        uses: melusina-org/setup-macports@v1

      - name: Install icu4c on macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          sudo port -v install icu
```

then they configure msbuild to copy the binary into the ouput:
```csproj
  <!--
    This assumes that icu4c libs are installed under "/opt/local/lib" on macOS. This is the default
    location for libs that MacPorts installs. If we need to start bundling icu4c libs from
    somewhere other than "/opt/local/lib", this path and some other paths in the build scripts will
    need to be updated. We have to bundle the icu4c libs somehow unless macOS starts to include them
    by default.
    -->
  <ItemGroup>
    <Content Include="/opt/local/lib/libicu*.??.dylib" Condition="$([MSBuild]::IsOsPlatform('macOS'))">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
```

we could do the same thing, we could probably just build all versions on mac and it'll work just fine, we're already building all versions on Linux and that works fine.

- [x] #1006
